# -*- coding: utf-8 -*-
"""Plot Densité sans Viellisement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-plwFOz5UNMtDXLVAKxxs4h7zGbrXRG
"""

from scipy.stats import expon
import numpy as np
import matplotlib.pyplot as plt

# fonction pour calculer f(x) pour la densité du modèle sans viellisement
def calcul_densite(alpha, lambda_, x):
  f = np.zeros(len(x))

  for point in range(len(x)):
    for index in range(len(alpha)):
        f[point] += alpha[index] * expon.pdf(scale=(1/lambda_[index]), x=x[point])
  return f

alpha_vrai = [0.15, 0.25, 0.2, 0.1, 0.3]
lambda_vrai = [5, 7, 2, 9, 8]

alpha_0 = [0.10, 0.20, 0.3, 0.15, 0.25]
lambda_0 = [7, 5, 3, 10, 6]

alpha_1000 = [0.12827427, 0.24130557, 0.123822, 0.19270622, 0.31389194]
lambda_1000 = [7.1257111, 6.16985575, 1.56813125, 8.33574549, 6.74052807]

support = np.linspace(start=1, stop=10, num=100)

f_true = calcul_densite(alpha=alpha_vrai, lambda_=lambda_vrai, x=support)
f_0 = calcul_densite(alpha=alpha_0, lambda_=lambda_0, x=support)
f_1000 = calcul_densite(alpha=alpha_1000, lambda_=lambda_1000, x=support)

plt.plot(support, f_true, label='Vraie densité des machines', linewidth=1.0)
plt.plot(support, f_0, label='Densité initiale sans itération', ls='dotted', linewidth=1.0)
plt.plot(support, f_1000, label='Densité après 1000 itérations', ls='--', linewidth=1.0)

plt.legend()
plt.show()